# Generated by Django 3.1.13 on 2021-08-17 02:18

from django.db import migrations, models
import djongo.models.fields
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', djongo.models.fields.EmbeddedField(model_container=todos.models.User)),
                ('allTasks', djongo.models.fields.ArrayField(model_container=todos.models.Todo)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
